steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]

substitutions:
  _LOCATION: asia-northeast1
  _REPOSITORY: web-game

images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

# gcloud builds submit --config=cloudbuild.yaml --substitutions=_IMAGE="bingo:v1.0.0" .